alias lf='ls -F'
alias la='ls -a'
alias ll='ls -l'
alias subl='~/Desktop/Sublime\ Text\ Build\ 3114\ x64/subl.exe'
alias gs='git status'
alias ga='git add .'
alias gcm='git commit -m'
alias gp='git push origin master'
